### ISSUE TITLE
Rozwalenie tabliczki AtomicDisassemblerem crashuje serwer

### ISSUE THREAD

**Issue by marcin212** [StarChasers/Modpack#168]
<08:59:36> "Nikos": wyjebało serwer po tym jak rozwaliłem tabliczkę kilofem
<09:00:19> "Nikos": idę się przespać chyba xd...
```
java.lang.IllegalArgumentException: Stack can not be invalid!
	at net.minecraftforge.oredict.OreDictionary.getOreIDs(OreDictionary.java:440)
	at mekanism.common.OreDictCache.getOreDictName(OreDictCache.java:34)
	at mekanism.common.util.MekanismUtils.getOreDictName(MekanismUtils.java:458)
	at mekanism.common.item.ItemAtomicDisassembler.onBlockStartBreak(ItemAtomicDisassembler.java:131)
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:305)
	at net.minecraft.server.management.PlayerInteractionManager.func_73075_a(PlayerInteractionManager.java:112)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:272)
	at net.minecraft.world.World.func_72866_a(World.java:1965)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840)
	at net.minecraft.world.World.func_72870_g(World.java:1934)
	at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:650)
	at net.minecraft.world.World.func_72939_s(World.java:1724)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by PlayerWithoutName** [comment]
Jak patrze na ten stacktrace to to wyglada jakby on chcial znalezc "rudy tabliczki" w poblizu xd np. przy vein

**Comment by marcin212** [comment]
Dokładnie tak jak mówisz. Tylko czemu stack jest ```invalid``` kiedy go rozwalasz? (teraz stack nie może być nullem)
