### ISSUE TITLE
[IE] java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by Acerixx** [StarChasers/Modpack#76]
java.lang.NoSuchMethodError: blusunrize.immersiveengineering.client.ClientEventHandler.renderAllIEConnections(F)V
	at unwrittenfun.minecraft.immersiveintegration.client.renderers.TileRenderMETransformer.renderDynamic(TileRenderMETransformer.java:22)
	at blusunrize.immersiveengineering.client.render.TileRenderIE.func_147500_a(TileRenderIE.java:13)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:100)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147544_a(SourceFile:92)
	at fastcraft.c.s.a(F:544)
	at fastcraft.HC.al(F:137)
	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1224)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1015)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by marcin212** [comment]
mam to samo

**Comment by marcin212** [comment]
fixed
