### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Acerixx** [StarChasers/Modpack#81]
java.lang.IllegalArgumentException: Rotation for vertical direction is not defined
	at com.cout970.magneticraft.api.util.VecIntUtil.getRotatedOffset(VecIntUtil.java:148)
	at com.cout970.magneticraft.tileentity.multiblock.controllers.TileRefinery.getRenderBoundingBox(TileRefinery.java:120)
	at fastcraft.c.s.a(F:542)
	at fastcraft.HC.al(F:137)
	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1224)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1015)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by marcin212** [comment]
Jak to zrobić?
